### ISSUE TITLE
How can I configure container images for jobs?

### ISSUE THREAD

**Issue by hartwig-wutscher-ibm** [redhat-actions/openshift-actions-runner-chart#18]
I have some steps that run in a custom Image, e.g.
```
  test-and-sonar-scan:
    environment: default
    runs-on: [ self-hosted ]
    container:
      image: sonarsource/sonar-scanner-cli:4
   steps:
     [ ... ]
```

This results in the following error:

```
Current runner version: '2.284.0'
Runner name: 'bwi-689857b555-p59kf'
Runner group name: 'bwi-runner'
Machine name: 'bwi-689857b555-p59kf'
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f)
Error: docker: command not found
```

I've tried using the podman runner image adapted so it uses podaman as a drop-in replacement for, but that opened a whole host of new issues.

Is there a proper way to configer the runner to be running a job in  a defined container?
